openai:
  model: gpt-3.5-turbo
  maxTokens: 150
  temperature: 0
  max-completions: 1
openai.api:
  key: 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
  url: https://api.openai.com/v1/chat/completions
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG